---
title: "Parametic"
author: "Paidamoyo Chapfuwa"
date: "1/30/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ovarian Cancer Survival Analysis


```{r}
library(survival)
data(ovarian)
head(ovarian)
S1 <- Surv(ovarian$futime, ovarian$fustat)
ovarian.surv<- survfit(S1~1, ovarian)
summary(ovarian.surv)
plot(ovarian.surv,xlab="t",ylab=expression(hat(S)*"(t)"), lty=2:3)

##Exponential
#h(t) = l, S(t) = exp(-lt)
#l = exp(-(intercept))
ovarian.exp<-survreg(S1~1  , ovarian, dist='exponential')
summary(ovarian.exp)
intercept <- coefficients(ovarian.exp)[['(Intercept)']]
lambda <- exp(-intercept)
T_survival <- seq(0, 1210, by=0.1)
lines(T_survival,1-pexp(T_survival,lambda),xlab="t",ylab=expression(hat(S)*"(t)"), col='blue')

##Weibull
#h(t) = a*y*t^(y-1), S(t) = exp(-at^y)
#a = exp(-(intercept)y)
#y = 1/scale
ovarian.wei<-survreg(S1~1  , ovarian, dist='weibull',scale=0)
summary(ovarian.wei)
intercept <- coefficients(ovarian.wei)[['(Intercept)']]
scale <- ovarian.wei$scale
gamma <- 1/scale
T_survival <- seq(0, 1210, by=0.1)
lines(T_survival,1-pweibull(T_survival,gamma,exp(intercept)),xlab="t",ylab=expression(hat(S)*"(t)"), col='red')
legend(0, 0.4, legend=c("KaplanMeier", "Exponential", "Weibull"), lty = c(1,1,1), col = c('black', 'blue', 'red'))
```
